export const wordDatabase = [
  // --- FOOD ---
  { category: "Food", word: "Pizza", imposterWord: "Burger" },
  { category: "Food", word: "Burger", imposterWord: "Hot Dog" },
  { category: "Food", word: "Chocolate", imposterWord: "Brownie" },
  { category: "Food", word: "Ice Cream", imposterWord: "Frozen Yogurt" },
  { category: "Food", word: "Sushi", imposterWord: "Sashimi" },
  { category: "Food", word: "Banana", imposterWord: "Plantain" },
  { category: "Food", word: "Popcorn", imposterWord: "Nachos" },
  { category: "Food", word: "Taco", imposterWord: "Burrito" },
  { category: "Food", word: "Noodles", imposterWord: "Pasta" },
  { category: "Food", word: "Biryani", imposterWord: "Pulao" },
  { category: "Food", word: "Waffles", imposterWord: "Pancake" },
  { category: "Food", word: "Cheese", imposterWord: "Butter" },
  { category: "Food", word: "Spaghetti", imposterWord: "Macaroni" },
  { category: "Food", word: "Hot Dog", imposterWord: "Sausage" },
  { category: "Food", word: "Croissant", imposterWord: "Muffin" },
  { category: "Food", word: "Mango", imposterWord: "Papaya" },
  { category: "Food", word: "Strawberry", imposterWord: "Raspberry" },
  { category: "Food", word: "Avocado", imposterWord: "Guacamole" },
  { category: "Food", word: "Donut", imposterWord: "Bagel" },
  { category: "Food", word: "Garlic Bread", imposterWord: "Breadstick" },
  { category: "Food", word: "Samosa", imposterWord: "Spring Roll" },
  { category: "Food", word: "Curry", imposterWord: "Stew" },
  { category: "Food", word: "Butter Chicken", imposterWord: "Tikka Masala" },
  { category: "Food", word: "Ramen", imposterWord: "Pho" },
  { category: "Food", word: "Lasagna", imposterWord: "Casserole" },
  { category: "Food", word: "Pancake", imposterWord: "Crepe" },
  
  // --- ANIMALS ---
  { category: "Animals", word: "Elephant", imposterWord: "Rhino" },
  { category: "Animals", word: "Lion", imposterWord: "Tiger" },
  { category: "Animals", word: "Giraffe", imposterWord: "Camel" },
  { category: "Animals", word: "Penguin", imposterWord: "Puffin" },
  { category: "Animals", word: "Cat", imposterWord: "Kitten" },
  { category: "Animals", word: "Dolphin", imposterWord: "Whale" },
  { category: "Animals", word: "Kangaroo", imposterWord: "Wallaby" },
  { category: "Animals", word: "Monkey", imposterWord: "Chimpanzee" },
  { category: "Animals", word: "Dog", imposterWord: "Wolf" },
  { category: "Animals", word: "Panda", imposterWord: "Bear" },
  { category: "Animals", word: "Shark", imposterWord: "Barracuda" },
  { category: "Animals", word: "Frog", imposterWord: "Toad" },
  { category: "Animals", word: "Koala", imposterWord: "Sloth" },
  { category: "Animals", word: "Tiger", imposterWord: "Leopard" },
  { category: "Animals", word: "Bear", imposterWord: "Grizzly" },
  { category: "Animals", word: "Rabbit", imposterWord: "Hare" },
  { category: "Animals", word: "Eagle", imposterWord: "Hawk" },
  { category: "Animals", word: "Octopus", imposterWord: "Squid" },
  { category: "Animals", word: "Chameleon", imposterWord: "Iguana" },
  { category: "Animals", word: "Squirrel", imposterWord: "Chipmunk" },
  { category: "Animals", word: "Fox", imposterWord: "Coyote" },
  { category: "Animals", word: "Cheetah", imposterWord: "Jaguar" },
  { category: "Animals", word: "Zebra", imposterWord: "Horse" },
  { category: "Animals", word: "Owl", imposterWord: "Falcon" },
  { category: "Animals", word: "Hamster", imposterWord: "Guinea Pig" },
  { category: "Animals", word: "Turtle", imposterWord: "Tortoise" },
  { category: "Animals", word: "Wolf", imposterWord: "Husky" },
  { category: "Animals", word: "Gorilla", imposterWord: "Orangutan" },
  { category: "Animals", word: "Crocodile", imposterWord: "Alligator" },
  { category: "Animals", word: "Hippo", imposterWord: "Walrus" },
  { category: "Animals", word: "Rhino", imposterWord: "Buffalo" },
  { category: "Animals", word: "Deer", imposterWord: "Antelope" },
  { category: "Animals", word: "Horse", imposterWord: "Donkey" },
  { category: "Animals", word: "Cow", imposterWord: "Buffalo" },
  { category: "Animals", word: "Sheep", imposterWord: "Goat" },
  { category: "Animals", word: "Pig", imposterWord: "Boar" },
  { category: "Animals", word: "Snake", imposterWord: "Lizard" },
  { category: "Animals", word: "Parrot", imposterWord: "Cockatoo" },
  { category: "Animals", word: "Flamingo", imposterWord: "Crane" },
  { category: "Animals", word: "Peacock", imposterWord: "Pheasant" },
  { category: "Animals", word: "Whale", imposterWord: "Dolphin" },
  { category: "Animals", word: "Butterfly", imposterWord: "Moth" },

  // --- OBJECTS ---
  { category: "Objects", word: "Smartphone", imposterWord: "Tablet" },
  { category: "Objects", word: "Bicycle", imposterWord: "Scooter" },
  { category: "Objects", word: "Umbrella", imposterWord: "Raincoat" },
  { category: "Objects", word: "Clock", imposterWord: "Watch" },
  { category: "Objects", word: "Backpack", imposterWord: "Suitcase" },
  { category: "Objects", word: "Mirror", imposterWord: "Window" },
  { category: "Objects", word: "Key", imposterWord: "Lock" },
  { category: "Objects", word: "Guitar", imposterWord: "Ukulele" },
  { category: "Objects", word: "Toilet Paper", imposterWord: "Tissue" },
  { category: "Objects", word: "Spoon", imposterWord: "Fork" },
  { category: "Objects", word: "Pillow", imposterWord: "Cushion" },
  { category: "Objects", word: "Socks", imposterWord: "Gloves" },
  { category: "Objects", word: "Scissors", imposterWord: "Knife" },
  { category: "Objects", word: "Headphones", imposterWord: "Earbuds" },
  { category: "Objects", word: "Laptop", imposterWord: "Desktop" },
  { category: "Objects", word: "Sunglasses", imposterWord: "Goggles" },
  { category: "Objects", word: "Lipstick", imposterWord: "Lip Gloss" },
  { category: "Objects", word: "Coffee Mug", imposterWord: "Teacup" },
  { category: "Objects", word: "Wallet", imposterWord: "Purse" },
  { category: "Objects", word: "Ring", imposterWord: "Bracelet" },
  { category: "Objects", word: "Hammer", imposterWord: "Wrench" },
  { category: "Objects", word: "Toothbrush", imposterWord: "Comb" },
  { category: "Objects", word: "Blanket", imposterWord: "Towel" },
  { category: "Objects", word: "Telescope", imposterWord: "Binoculars" },
  { category: "Objects", word: "Balloon", imposterWord: "Bubble" },
  { category: "Objects", word: "Hairdryer", imposterWord: "Straightener" },
  { category: "Objects", word: "Bed", imposterWord: "Couch" },
  { category: "Objects", word: "Bedsheet", imposterWord: "Curtain" },
  { category: "Objects", word: "TV", imposterWord: "Monitor" },

  // --- PLACES ---
  { category: "Places", word: "Beach", imposterWord: "Pool" },
  { category: "Places", word: "Cinema", imposterWord: "Theater" },
  { category: "Places", word: "School", imposterWord: "College" },
  { category: "Places", word: "Hospital", imposterWord: "Clinic" },
  { category: "Places", word: "Airport", imposterWord: "Train Station" },
  { category: "Places", word: "Gym", imposterWord: "Yoga Studio" },
  { category: "Places", word: "Library", imposterWord: "Bookstore" },
  { category: "Places", word: "Restaurant", imposterWord: "Cafe" },
  { category: "Places", word: "Toilet", imposterWord: "Bathroom" },
  { category: "Places", word: "Oasis", imposterWord: "Lagoon" },
  { category: "Places", word: "Jail", imposterWord: "Prison" },
  { category: "Places", word: "Museum", imposterWord: "Gallery" },
  { category: "Places", word: "Supermarket", imposterWord: "Grocery Store" },
  { category: "Places", word: "Church", imposterWord: "Temple" },
  { category: "Places", word: "Castle", imposterWord: "Palace" },
  { category: "Places", word: "Office", imposterWord: "Cubicle" },
  { category: "Places", word: "Hotel", imposterWord: "Motel" },
  { category: "Places", word: "Bakery", imposterWord: "Patisserie" },
  { category: "Places", word: "Farm", imposterWord: "Ranch" },
  { category: "Places", word: "Casino", imposterWord: "Arcade" },
  { category: "Places", word: "Zoo", imposterWord: "Safari" },
  { category: "Places", word: "Kitchen", imposterWord: "Pantry" },
  { category: "Places", word: "Bedroom", imposterWord: "Living Room" },
  { category: "Places", word: "Forest", imposterWord: "Jungle" },
  { category: "Places", word: "Space Station", imposterWord: "Satellite" },
  { category: "Places", word: "Desert", imposterWord: "Tundra" },
  { category: "Places", word: "Road", imposterWord: "Highway" },
  { category: "Places", word: "Shop", imposterWord: "Boutique" },
  { category: "Places", word: "Mall", imposterWord: "Plaza" },

  // --- JOBS ---
  { category: "Jobs", word: "Doctor", imposterWord: "Nurse" },
  { category: "Jobs", word: "Teacher", imposterWord: "Professor" },
  { category: "Jobs", word: "Firefighter", imposterWord: "Paramedic" },
  { category: "Jobs", word: "Chef", imposterWord: "Baker" },
  { category: "Jobs", word: "Pilot", imposterWord: "Captain" },
  { category: "Jobs", word: "Astronaut", imposterWord: "Cosmonaut" },
  { category: "Jobs", word: "Artist", imposterWord: "Sculptor" },
  { category: "Jobs", word: "Police Officer", imposterWord: "Security Guard" },
  { category: "Jobs", word: "Influencer", imposterWord: "Blogger" },
  { category: "Jobs", word: "Politician", imposterWord: "Diplomat" },
  { category: "Jobs", word: "Janitor", imposterWord: "Cleaner" },
  { category: "Jobs", word: "Lawyer", imposterWord: "Judge" },
  { category: "Jobs", word: "Actor", imposterWord: "Director" },
  { category: "Jobs", word: "Musician", imposterWord: "Singer" },
  { category: "Jobs", word: "Plumber", imposterWord: "Electrician" },
  { category: "Jobs", word: "Barber", imposterWord: "Hairstylist" },
  { category: "Jobs", word: "Farmer", imposterWord: "Gardener" },
  { category: "Jobs", word: "Soldier", imposterWord: "Marine" },
  { category: "Jobs", word: "Detective", imposterWord: "Spy" },
  { category: "Jobs", word: "Programmer", imposterWord: "Hacker" },
  { category: "Jobs", word: "Waiter", imposterWord: "Bartender" },
  { category: "Jobs", word: "Model", imposterWord: "Photographer" },
  { category: "Jobs", word: "Priest", imposterWord: "Monk" },
  { category: "Jobs", word: "Sailor", imposterWord: "Pirate" },

  // --- SUPERHEROES ---
  { category: "Superheroes", word: "Batman", imposterWord: "Iron Man" },
  { category: "Superheroes", word: "Superman", imposterWord: "Captain America" },
  { category: "Superheroes", word: "Spiderman", imposterWord: "Ant-Man" },
  { category: "Superheroes", word: "Iron Man", imposterWord: "Batman" },
  { category: "Superheroes", word: "Thor", imposterWord: "Hercules" },
  { category: "Superheroes", word: "Hulk", imposterWord: "Thing" },
  { category: "Superheroes", word: "Captain America", imposterWord: "Superman" },
  { category: "Superheroes", word: "Black Widow", imposterWord: "Catwoman" },
  { category: "Superheroes", word: "Deadpool", imposterWord: "Punisher" },
  { category: "Superheroes", word: "Wolverine", imposterWord: "Beast" },
  { category: "Superheroes", word: "Wonder Woman", imposterWord: "Supergirl" },
  { category: "Superheroes", word: "Flash", imposterWord: "Quicksilver" },
  { category: "Superheroes", word: "Aquaman", imposterWord: "Namor" },
  { category: "Superheroes", word: "Joker", imposterWord: "Riddler" },
  { category: "Superheroes", word: "Thanos", imposterWord: "Darkseid" },
  { category: "Superheroes", word: "Loki", imposterWord: "Mystique" },

  // --- BRANDS & COMPANIES ---
  { category: "Brands & Companies", word: "Google", imposterWord: "Bing" },
  { category: "Brands & Companies", word: "Apple", imposterWord: "Samsung" },
  { category: "Brands & Companies", word: "Nike", imposterWord: "Adidas" },
  { category: "Brands & Companies", word: "Tesla", imposterWord: "Rivian" },
  { category: "Brands & Companies", word: "Starbucks", imposterWord: "Dunkin" },
  { category: "Brands & Companies", word: "McDonald's", imposterWord: "Burger King" },
  { category: "Brands & Companies", word: "Instagram", imposterWord: "Snapchat" },
  { category: "Brands & Companies", word: "Amazon", imposterWord: "Flipkart" },
  { category: "Brands & Companies", word: "Coca-Cola", imposterWord: "Pepsi" },
  { category: "Brands & Companies", word: "IKEA", imposterWord: "Wayfair" },
  { category: "Brands & Companies", word: "Gucci", imposterWord: "Prada" },
  { category: "Brands & Companies", word: "Pepsi", imposterWord: "Sprite" },
  { category: "Brands & Companies", word: "Adidas", imposterWord: "Puma" },
  { category: "Brands & Companies", word: "Samsung", imposterWord: "Xiaomi" },
  { category: "Brands & Companies", word: "Netflix", imposterWord: "Hulu" },
  { category: "Brands & Companies", word: "Disney", imposterWord: "Pixar" },

  // --- FUNNY & SPICY ---
  { category: "Funny & Spicy", word: "Condom", imposterWord: "Balloon" },
  { category: "Funny & Spicy", word: "Vibrator", imposterWord: "Massage Gun" },
  { category: "Funny & Spicy", word: "Strip Club", imposterWord: "Nightclub" },
  { category: "Funny & Spicy", word: "Tinder", imposterWord: "Bumble" },
  { category: "Funny & Spicy", word: "Hickey", imposterWord: "Bruise" },
  { category: "Funny & Spicy", word: "Fart", imposterWord: "Burp" },
  { category: "Funny & Spicy", word: "Kama Sutra", imposterWord: "Yoga" },
  { category: "Funny & Spicy", word: "Stripper", imposterWord: "Dancer" },
  { category: "Funny & Spicy", word: "One Night Stand", imposterWord: "Hookup" },
  { category: "Funny & Spicy", word: "Bikini", imposterWord: "Lingerie" },
  { category: "Funny & Spicy", word: "Sexting", imposterWord: "Flirting" },
  { category: "Funny & Spicy", word: "Underwear", imposterWord: "Boxers" },
  { category: "Funny & Spicy", word: "Thong", imposterWord: "G-String" },
  { category: "Funny & Spicy", word: "Pornstar", imposterWord: "Adult Actor" },
  { category: "Funny & Spicy", word: "Booty", imposterWord: "Butt" },
  { category: "Funny & Spicy", word: "Orgasm", imposterWord: "Climax" },
  { category: "Funny & Spicy", word: "Blindfold", imposterWord: "Mask" },
  { category: "Funny & Spicy", word: "Handcuffs", imposterWord: "Rope" },
  { category: "Funny & Spicy", word: "Nipple", imposterWord: "Belly Button" },
  { category: "Funny & Spicy", word: "Lubricant", imposterWord: "Oil" },
  { category: "Funny & Spicy", word: "Flirt", imposterWord: "Tease" },
  { category: "Funny & Spicy", word: "Sugar Daddy", imposterWord: "Gold Digger" },
  { category: "Funny & Spicy", word: "Lap Dance", imposterWord: "Twerk" },
  { category: "Funny & Spicy", word: "Viagra", imposterWord: "Energy Drink" },
  { category: "Funny & Spicy", word: "French Kiss", imposterWord: "Makeout" },
  { category: "Funny & Spicy", word: "Walk of Shame", imposterWord: "Hangover" }
];

export function getRandomWord() {
  const index = Math.floor(Math.random() * wordDatabase.length);
  return wordDatabase[index];
}
